### ISSUE TITLE
Example build tool

### ISSUE THREAD

**Issue by bensu** [roman01la/prum#3]
This issue is not related to the project but rather to how to use the dependency. Which cljs build tool can I use? I can't compile prum with the latest versions of cljsbuild and figwheel because of this line:

https://github.com/roman01la/prum/blob/preact/src/prum/core.cljs#L5

Do you have any example projects with a project.clj with the right config to compile prum or do I have to use a custom build script with the latest lojurescript version?

**Comment by roman01la** [comment]
Hi! Prum requires to use latest ClojureScript with support for [`:npm-deps`](https://github.com/clojure/clojurescript-site/blob/master/content/reference/compiler-options.adoc#npm-deps) which means you have to have installed NPM and add `:install-deps true` to compiler options in your build config.

Once you add this option and restart the build, it should install NPM dependency automatically and build the project. Let me know if it worked for you.

**Comment by bensu** [comment]
Thanks! I'll try and let you know.

**Comment by bensu** [comment]
Thanks! I'll try and let you know.
